In [1]:
print('monir')

monir


In [2]:
age =24

In [3]:
print(f"I am monir hosen and my age is {age}")

I am monir hosen and my age is 24


# Installing Numpy 

In [4]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


# Why Not Python List?





In [11]:
import numpy as np 

In [ ]:
# Why Not Python List?
numbers=[1,2,3,4,5,6]
# If I want to multiply by 2 then I have to use loop for that.
#  But in numpy I can do it easily.

In [ ]:
# using python list 
result=[]
for a in numbers:
    num=a*2
    result.append(num)
print(result)

In [10]:
print(result)

[2, 4, 6, 8, 10, 12]


In [12]:
# Now let's see how can we do it more precisely using numpy.
num_result=np.array(numbers)*2

In [13]:
print(result)

[2, 4, 6, 8, 10, 12]


In [15]:
# LET'S see another example of numpy 
# if we want to add two list then list concatenation is used but in numpy we can do it 
# using addition operator.

a=[1,2,3,4]
b=[2,3,4,5]
a+b

[1, 2, 3, 4, 2, 3, 4, 5]

In [16]:
# in numpy we can do it using addition operator

In [ ]:
a=np.array([23,4,6])
b=np.array([4,5,6])
a+b 

array([27,  9, 12])

In [ ]:
type(a+b)

numpy.ndarray

## there are four main reasons
* 1. Python storess references to objects in memory. every integer is a separate python object
    while numpy stores raw data in a continuous block of memory.
 * 2. Numpy is written in C. Python loop is slow because it is an interpreted language. Numpy is written in C and C is a compiled language. 
*  3. Numpy uses vectorization which is a technique of performing operations on entire arrays instead of individual elements. 
* 4. SIMD optimization. Numpy uses SIMD optimization which is a technique of performing operations on multiple data points simultaneously.

In [20]:
import numpy as np 


In [21]:
print(np.__version__)

2.1.3


### First Numpy Array

### Method 1 (using list)

In [23]:
marks=np.array([45,56,7,56,7,8,99])
print(marks)

[45 56  7 56  7  8 99]


### Method 2 (*using tuple*)

In [25]:
arr=np.array((1,2,3,4,2,1))
print(arr)

[1 2 3 4 2 1]


### Method-3 using nested list (2d array)

In [28]:
matrix=np.array([[1,2,3],[2,3,4]])

In [29]:
print(matrix )

[[1 2 3]
 [2 3 4]]


**Creating arrays of zeros**

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
# 2D zeros

np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Use Cases

- Machine Learning

- Initialize weights

- Image Processing

- Create blank image

- Simulation

- Initialize values

**Creating arrays of ONES**

In [32]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.ones(((3,4,5)))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])