In [3]:
print('monir')

monir


In [4]:
age =24

In [5]:
print(f"I am monir hosen and my age is {age}")

I am monir hosen and my age is 24


# Installing Numpy 

In [6]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


# Why Not Python List?





In [7]:
import numpy as np 

In [8]:
# Why Not Python List?
numbers=[1,2,3,4,5,6]
# If I want to multiply by 2 then I have to use loop for that.
#  But in numpy I can do it easily.

In [9]:
# using python list 
result=[]
for a in numbers:
    num=a*2
    result.append(num)
print(result)

[2, 4, 6, 8, 10, 12]


In [10]:
print(result)

[2, 4, 6, 8, 10, 12]


In [11]:
# Now let's see how can we do it more precisely using numpy.
num_result=np.array(numbers)*2

In [12]:
print(result)

[2, 4, 6, 8, 10, 12]


In [13]:
# LET'S see another example of numpy 
# if we want to add two list then list concatenation is used but in numpy we can do it 
# using addition operator.

a=[1,2,3,4]
b=[2,3,4,5]
a+b

[1, 2, 3, 4, 2, 3, 4, 5]

In [14]:
# in numpy we can do it using addition operator

In [15]:
a=np.array([23,4,6])
b=np.array([4,5,6])
a+b 

array([27,  9, 12])

In [16]:
type(a+b)

numpy.ndarray

## there are four main reasons
* 1. Python storess references to objects in memory. every integer is a separate python object
    while numpy stores raw data in a continuous block of memory.
 * 2. Numpy is written in C. Python loop is slow because it is an interpreted language. Numpy is written in C and C is a compiled language. 
*  3. Numpy uses vectorization which is a technique of performing operations on entire arrays instead of individual elements. 
* 4. SIMD optimization. Numpy uses SIMD optimization which is a technique of performing operations on multiple data points simultaneously.

In [17]:
import numpy as np 


In [18]:
print(np.__version__)

2.1.3


### First Numpy Array

### Method 1 (using list)

In [19]:
marks=np.array([45,56,7,56,7,8,99])
print(marks)

[45 56  7 56  7  8 99]


### Method 2 (*using tuple*)

In [20]:
arr=np.array((1,2,3,4,2,1))
print(arr)

[1 2 3 4 2 1]


### Method-3 using nested list (2d array)

In [21]:
matrix=np.array([[1,2,3],[2,3,4]])

In [22]:
print(matrix )

[[1 2 3]
 [2 3 4]]


**Creating arrays of zeros**

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
# 2D zeros

np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Use Cases

- Machine Learning

- Initialize weights

- Image Processing

- Create blank image

- Simulation

- Initialize values

**Creating arrays of ONES**

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones(((3,4,5)))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### **Empty Array**

In [28]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.empty(((2,5,2)))

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 9.34609111e-307],
        [1.33511018e-306, 1.33511969e-306],
        [6.23037996e-307, 6.23053954e-307],
        [9.34609790e-307, 8.45593934e-307]],

       [[9.34600963e-307, 1.86921143e-306],
        [6.23061763e-307, 1.60220393e-306],
        [7.56589622e-307, 1.33510882e-306],
        [1.37961370e-306, 1.69118515e-306],
        [7.56598449e-307, 1.42410974e-306]]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(5,9)

array([5, 6, 7, 8])

In [32]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

**Creating Evenly Spaced Values with linspace()**

- Unlike arange(), you specify how many values you want, not the step size.

In [33]:
np.linspace(5,30,5)

array([ 5.  , 11.25, 17.5 , 23.75, 30.  ])

**Creating an Identity Matrix**

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Real-World Examples

In [35]:
marks=np.array([23,45,67,89,90])
print(marks)


[23 45 67 89 90]


In [36]:
temperature=np.array([45.6,2,3.4,34.3,36.7])

In [37]:
print(temperature)

[45.6  2.   3.4 34.3 36.7]


In [38]:
colors=np.array([
    [234,0,0],
    [0,234,0],
    [0,0,234]
])
print(colors)

[[234   0   0]
 [  0 234   0]
 [  0   0 234]]


In [39]:
image = np.array([
    [0, 128, 255],
    [64, 192, 32],
    [255, 0, 128]
])
# Each number represents pixel intensity (0 = black, 255 = white).

In [40]:
print(image)

[[  0 128 255]
 [ 64 192  32]
 [255   0 128]]


# Practice Excercises

In [49]:
#Create an array from 1–10.
np.arange(1,11)
#Create a 4×4 matrix of zeros.
np.zeros(4)
#Create a 3×5 matrix of ones.
np.ones((3,5))
#Create an identity matrix of size 5.
np.eye(5)
#Create even numbers from 2 to 20.
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
# Create 8 equally spaced numbers between 5 and 40.
np.linspace(5,40,8)

array([ 5., 10., 15., 20., 25., 30., 35., 40.])

In [56]:
# 
# Create a 2×3 matrix representing student marks.
marks =np.array([[3,4,5],[45,6,6]])
print(marks)

[[ 3  4  5]
 [45  6  6]]


In [58]:
#Create an RGB color palette.
rgb=np.array([[256,0,0],
              [0,256,0],
              [0,0,256]])
print(rgb)

[[256   0   0]
 [  0 256   0]
 [  0   0 256]]


In [61]:
# Create a blank 512×512 image using zeros().
np.zeros((512,512))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [63]:


#Create a 3×3 matrix using nested lists.
np.array([[3,4,5],[2,3,4],[3,5,6]])

array([[3, 4, 5],
       [2, 3, 4],
       [3, 5, 6]])

**Create a chessboard-like pattern using only zeros() and manual assignments (you'll improve this later with slicing).**

In [73]:
chess=np.zeros((8,8))

In [76]:
chess[0][1]=1
chess[1][0]=1

In [78]:
for i in range(0,8):
    for j in range(0,8):
        if (i %2==1 and j%2!=1) or (i%2!=1 and j%2==1):
            chess[i][j]=1
            

In [79]:
chess

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [82]:
np.ones(((2,3,3)))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [89]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [71]:
#Generate x-values from -5 to 5 using both arange() and linspace(), 
# then compare the outputs.

x=np.arange(-5,5)
y=np.linspace(-5,5,11)

In [67]:
x

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [72]:
y

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [92]:
np.linspace(3,7,10)

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])